export const carsData = [
  {
    id: 1,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 2,
    make: 'BMW',
    model: 'X5',
    engine: '3.0',
    year: 2005,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'SUV',
    img: '/images/bmw-x5.png'
  },
  {
    id: 3,
    make: 'Toyota',
    model: 'Prius',
    engine: '1.6',
    year: 2009,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'hatchback',
    img: 'images/toyota-prius.png'
  },
  {
    id: 4,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 5,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 6,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: true,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 7,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 8,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 9,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 10,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 11,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 12,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 13,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 14,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 15,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 16,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 17,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 18,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 19,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 20,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 21,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 22,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 23,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 24,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 25,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 26,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 27,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 28,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 29,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 30,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 31,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 32,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 33,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'hatchback',
    img: '/images/honda-fit.png'
  },
  {
    id: 34,
    make: 'Honda',
    model: 'Fit',
    engine: '2.0',
    year: 2015,
    gearbox: 'Автомат',
    drive: 'Задній',
    price: '300 000 uah',
    mileage: 100000,
    status: false,
    body: 'sedan',
    img: '/images/honda-fit.png'
  }
]
